title: Power of Effort
logo_img: /assets/img/icons/background.jpg
# favicon: /assets/favicon.ico
description: 개발이 그냥 아니 너무 하고싶어요! 
global_tags: jekyll theme simplex golasblog responsive html5
copyright: © Golasowski 2021

sass:
    style: compressed

collections:
    category:
        output: true
    authors:
        output: false

defaults:
  -
    scope:
      path: ""
      type: category
    values:
      layout: "category"